import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "./config/query-provider";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/toaster";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<div>
					<div className="w-full h-16 bg-orange-400 flex items-center p-4 text-white font-bold text-3xl ">
						<span>GlobalThings - Case1</span>
					</div>
					<div className="flex justify-center">
						<QueryProvider>{children}</QueryProvider>
						<Toaster />
					</div>
				</div>
			</body>
		</html>
	);
}
